# Generated by Django 4.2.6 on 2023-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudgro_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
