# Generated by Django 4.2.6 on 2023-10-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudgro_web', '0003_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media_img'),
        ),
    ]
